
if(!AI.photo)AI.photo=()=>svgI(`<defs><linearGradient id="ph9" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#0b2a4a"/><stop offset="1" stop-color="#001e36"/></linearGradient></defs><rect x="4" y="4" width="40" height="40" rx="8" fill="url(#ph9)"/><text x="24" y="31" font-size="19" font-weight="700" text-anchor="middle" fill="#31a8ff" font-family="Segoe UI,Arial">Ph</text>`);

/* ============================ MINI 3D ENGINE ============================ */
const M3={
 cube(){const v=[[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1],[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]];return {v,f:[[0,3,2,1],[4,5,6,7],[0,1,5,4],[2,3,7,6],[1,2,6,5],[0,4,7,3]]};},
 sphere(n=14){const v=[],f=[];for(let i=0;i<=n;i++){const a=i/n*Math.PI;for(let j=0;j<n*2;j++){const b=j/(n*2)*Math.PI*2;v.push([Math.sin(a)*Math.cos(b),Math.cos(a),Math.sin(a)*Math.sin(b)]);}}const m=n*2;for(let i=0;i<n;i++)for(let j=0;j<m;j++){const a=i*m+j,b=i*m+(j+1)%m;f.push([a,b,b+m,a+m]);}return {v,f};},
 cyl(n=20,top=1){const v=[],f=[];for(let j=0;j<n;j++){const b=j/n*Math.PI*2;v.push([Math.cos(b)*top,1,Math.sin(b)*top],[Math.cos(b),-1,Math.sin(b)]);}for(let j=0;j<n;j++){const k=(j+1)%n;f.push([j*2,k*2,k*2+1,j*2+1]);}f.push([...Array(n)].map((_,j)=>(n-1-j)*2));f.push([...Array(n)].map((_,j)=>j*2+1));return {v,f};},
 cone(){return M3.cyl(20,0.001);},
 torus(n=20,m=10){const v=[],f=[];for(let i=0;i<n;i++){const a=i/n*Math.PI*2;for(let j=0;j<m;j++){const b=j/m*Math.PI*2,r=1+.4*Math.cos(b);v.push([r*Math.cos(a),.4*Math.sin(b),r*Math.sin(a)]);}}for(let i=0;i<n;i++)for(let j=0;j<m;j++){const a=i*m+j,b=i*m+(j+1)%m,c2=((i+1)%n)*m+(j+1)%m,d=((i+1)%n)*m+j;f.push([a,d,c2,b]);}return {v,f};},
 plane(){return {v:[[-1,0,-1],[1,0,-1],[1,0,1],[-1,0,1]],f:[[3,2,1,0]]};},
 pyramid(){return {v:[[-1,-1,-1],[1,-1,-1],[1,-1,1],[-1,-1,1],[0,1,0]],f:[[0,1,2,3],[1,0,4],[2,1,4],[3,2,4],[0,3,4]]};}};
const M3N={cube:'Куб',sphere:'Сфера',cyl:'Цилиндр',cone:'Конус',torus:'Тор (пончик)',plane:'Плоскость',pyramid:'Пирамида'};
const M3C={};for(const k in M3)M3C[k]=M3[k]();
function scene3d(cv,opt={}){const x=cv.getContext('2d');const S={objs:[],cam:{yaw:.7,pitch:.45,dist:9},sel:-1,grid:opt.grid,bg:opt.bg||'#ddd',faces:[]};
 const rot=(p,r)=>{let[a,b,c]=p;let t;t=b*Math.cos(r[0])-c*Math.sin(r[0]);c=b*Math.sin(r[0])+c*Math.cos(r[0]);b=t;t=a*Math.cos(r[1])+c*Math.sin(r[1]);c=-a*Math.sin(r[1])+c*Math.cos(r[1]);a=t;t=a*Math.cos(r[2])-b*Math.sin(r[2]);b=a*Math.sin(r[2])+b*Math.cos(r[2]);a=t;return [a,b,c];};
 function view(p){const C=S.cam;let[a,b,c]=p;let t=a*Math.cos(C.yaw)-c*Math.sin(C.yaw);c=a*Math.sin(C.yaw)+c*Math.cos(C.yaw);a=t;t=b*Math.cos(C.pitch)-c*Math.sin(C.pitch);c=b*Math.sin(C.pitch)+c*Math.cos(C.pitch);b=t;return [a,b,c+C.dist];}
 function proj(p){const W=cv.width,H=cv.height,f=Math.min(W,H)*.9;const v=view(p);if(v[2]<.1)return null;return [W/2+v[0]/v[2]*f,H/2-v[1]/v[2]*f,v[2]];}
 S.world=(o,p)=>{const r=rot([p[0]*o.s[0],p[1]*o.s[1],p[2]*o.s[2]],o.r);return [r[0]+o.p[0],r[1]+o.p[1],r[2]+o.p[2]];};
 S.render=(hq)=>{const W=cv.width,H=cv.height;if(typeof S.bg==='string'){x.fillStyle=S.bg;x.fillRect(0,0,W,H);}else{const g=x.createLinearGradient(0,0,0,H);g.addColorStop(0,S.bg[0]);g.addColorStop(1,S.bg[1]);x.fillStyle=g;x.fillRect(0,0,W,H);}
  if(S.grid){x.strokeStyle=S.grid;x.lineWidth=1;for(let i=-10;i<=10;i++){const a=proj([i,0,-10]),b=proj([i,0,10]),c=proj([-10,0,i]),d=proj([10,0,i]);x.beginPath();if(a&&b){x.moveTo(a[0],a[1]);x.lineTo(b[0],b[1]);}if(c&&d){x.moveTo(c[0],c[1]);x.lineTo(d[0],d[1]);}x.stroke();}
   const o=proj([0,0,0]),xa=proj([2,0,0]),za=proj([0,0,2]);if(o&&xa&&za){x.lineWidth=2;x.strokeStyle='#e5484d';x.beginPath();x.moveTo(o[0],o[1]);x.lineTo(xa[0],xa[1]);x.stroke();x.strokeStyle='#30a46c';x.beginPath();x.moveTo(o[0],o[1]);x.lineTo(za[0],za[1]);x.stroke();}}
  if(hq){S.objs.forEach(o=>{const c=proj([o.p[0],0,o.p[2]]);if(c){x.fillStyle='rgba(0,0,0,.18)';x.beginPath();x.ellipse(c[0],c[1],Math.max(4,o.s[0]*cv.height*.6/c[2]),Math.max(2,o.s[2]*cv.height*.25/c[2]),0,0,7);x.fill();}});}
  const L=[.4,.8,-.45],faces=[];
  S.objs.forEach((o,oi)=>{const m=M3C[o.type];const wv=m.v.map(p=>S.world(o,p));const pv=wv.map(proj);
   m.f.forEach(f=>{if(f.some(i=>!pv[i]))return;const a=wv[f[0]],b=wv[f[1]],c=wv[f[2]];const u=[b[0]-a[0],b[1]-a[1],b[2]-a[2]],v=[c[0]-a[0],c[1]-a[1],c[2]-a[2]];let n=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]];const nl=Math.hypot(...n)||1;n=n.map(q=>q/nl);
    const pts=f.map(i=>pv[i]);let area=0;for(let i=0;i<pts.length;i++){const p=pts[i],q=pts[(i+1)%pts.length];area+=p[0]*q[1]-q[0]*p[1];}if(area>0&&o.type!=='plane')return;
    const ll=Math.max(0,-(n[0]*L[0]+n[1]*L[1]+n[2]*L[2]));const z=pts.reduce((s,p)=>s+p[2],0)/pts.length;faces.push({pts,z,oi,sh:.35+.65*(o.type==='plane'?Math.abs(ll)||.7:ll)});});});
  faces.sort((a,b)=>b.z-a.z);S.faces=faces;
  for(const f of faces){const o=S.objs[f.oi];const col=o.c;const r=parseInt(col.slice(1,3),16),g=parseInt(col.slice(3,5),16),b=parseInt(col.slice(5,7),16);const k=f.sh*(o.mat==='metal'?1.25:1);
   x.fillStyle=`rgb(${Math.min(255,r*k)|0},${Math.min(255,g*k)|0},${Math.min(255,b*k)|0})`;x.beginPath();f.pts.forEach((p,i)=>i?x.lineTo(p[0],p[1]):x.moveTo(p[0],p[1]));x.closePath();x.fill();
   if(!hq){x.strokeStyle=f.oi===S.sel?(opt.selCol||'#ff9f1c'):(opt.wire||'rgba(0,0,0,.08)');x.lineWidth=f.oi===S.sel?1.6:1;x.stroke();}else{x.strokeStyle=x.fillStyle;x.lineWidth=.6;x.stroke();}}};
 S.pick=(px,py)=>{for(let i=S.faces.length-1;i>=0;i--){const p=S.faces[i].pts;let ins=false;for(let a=0,b=p.length-1;a<p.length;b=a++){if((p[a][1]>py)!==(p[b][1]>py)&&px<(p[b][0]-p[a][0])*(py-p[a][1])/(p[b][1]-p[a][1])+p[a][0])ins=!ins;}if(ins)return S.faces[i].oi;}return -1;};
 S.camVec=()=>{const C=S.cam;return {right:[Math.cos(C.yaw),0,-Math.sin(C.yaw)],fwd:[Math.sin(C.yaw),0,Math.cos(C.yaw)]};};
 S.add=(type,c)=>{S.objs.push({type,p:[(Math.random()-.5)*3,1,(Math.random()-.5)*3],r:[0,0,0],s:[1,1,1],c:c||'#4c9be8',name:M3N[type]+' '+(S.objs.length+1)});S.sel=S.objs.length-1;};
 S.toObj=()=>{let out='# Windows11WEB 3D export\n',base=1;S.objs.forEach(o=>{const m=M3C[o.type];out+=`o ${o.name.replace(/\s/g,'_')}\n`;m.v.forEach(p=>{const w=S.world(o,p);out+=`v ${w.map(n=>n.toFixed(4)).join(' ')}\n`;});m.f.forEach(f=>out+='f '+f.map(i=>i+base).join(' ')+'\n');base+=m.v.length;});return out;};
 // orbit
 let drag=null;cv.addEventListener('pointerdown',e=>{if(e.button===2||e.button===1||e.altKey||opt.orbitAny&&S.pick(...pos(e))<0){drag={x:e.clientX,y:e.clientY,orbit:true};cv.setPointerCapture(e.pointerId);}});
 const pos=e=>{const r=cv.getBoundingClientRect();return [(e.clientX-r.left)*cv.width/r.width,(e.clientY-r.top)*cv.height/r.height];};S.pos=pos;
 cv.addEventListener('pointermove',e=>{if(!drag||!drag.orbit)return;S.cam.yaw+=(e.clientX-drag.x)*.01;S.cam.pitch=Math.max(-1.4,Math.min(1.4,S.cam.pitch+(e.clientY-drag.y)*.01));drag.x=e.clientX;drag.y=e.clientY;S.render();});
 cv.addEventListener('pointerup',()=>drag=null);cv.addEventListener('contextmenu',e=>e.preventDefault());
 cv.addEventListener('wheel',e=>{e.preventDefault();S.cam.dist=Math.max(3,Math.min(40,S.cam.dist*(e.deltaY>0?1.1:.9)));S.render();},{passive:false});
 return S;}
function fitCanvas(cv,cb){new ResizeObserver(()=>{const r=cv.parentNode.getBoundingClientRect();if(!r.width)return;cv.width=r.width;cv.height=r.height;cb();}).observe(cv.parentNode);}
function savePng(cv,dir,name,app){const p=dir+'\\'+name;if(!VFS.isDir(dir))VFS.mkdir(dir);VFS.write(p,cv.toDataURL('image/png'));Shell.notify({title:app,body:'Сохранено: '+p,silent:true});Sound.pop();}
const PICS='C:\\Users\\User\\Pictures',DOCS='C:\\Users\\User\\Documents';

/* ---------- Paint 3D ---------- */
addCSS(`.p3{flex:1;display:flex;flex-direction:column;min-height:0;background:var(--mica-solid)}
.p3-top{display:flex;gap:4px;padding:6px 10px;border-bottom:1px solid var(--border);background:var(--surface)}
.p3-top button{padding:6px 12px;border-radius:6px;font-size:13px}.p3-top button:hover,.p3-top button.on{background:var(--hover)}
.p3-b{flex:1;display:flex;min-height:0}.p3-vp{flex:1;position:relative}.p3-vp canvas{position:absolute;inset:0;width:100%;height:100%}
.p3-side{width:250px;border-left:1px solid var(--border);padding:12px;overflow:auto;background:var(--surface);font-size:13px;display:flex;flex-direction:column;gap:10px}
.p3-side h4{font-size:14px;font-weight:600}.p3-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:6px}
.p3-grid button{padding:10px 2px;border-radius:8px;background:var(--surface-2);font-size:11px;display:flex;flex-direction:column;align-items:center;gap:4px}.p3-grid button:hover{background:var(--hover)}.p3-grid b{font-size:20px;font-weight:400}
.p3-col{display:flex;flex-wrap:wrap;gap:6px}.p3-col i{width:26px;height:26px;border-radius:50%;cursor:pointer;box-shadow:0 0 0 1px rgba(0,0,0,.2)}
.p3-side label{display:flex;justify-content:space-between;align-items:center;gap:8px}.p3-side input[type=range]{flex:1}`);
const P3COL=['#e74c3c','#ff9f1c','#ffd60a','#2ecc71','#1abc9c','#3498db','#4c9be8','#9b59b6','#ff6fb5','#ffffff','#95a5a6','#34495e','#8d6e63','#111111'];
storeApp('paint3d',{cat:'creative',dev:'Microsoft',rating:4.4,size:'210 МБ',desc:'Создавайте 3D-сцены из фигур: кубы, сферы, пончики. Цвета, материалы, вращение камеры и экспорт в PNG.',feat:['7 типов 3D-фигур','Перетаскивание, размер, поворот','Сохранение в «Изображения»']},{name:'Paint 3D',icon:AI.paint3d,keywords:'paint 3d пейнт 3д трехмерный модели',launch(){
 const root=el(`<div class="p3"><div class="p3-top"><button class="on">🧊 3D-фигуры</button><button data-a="bg">🎨 Холст</button><button data-a="demo">✨ Пример</button><button data-a="clear">🗑 Очистить</button><span style="flex:1"></span><button data-a="save">💾 Сохранить PNG</button></div><div class="p3-b"><div class="p3-vp"><canvas></canvas></div><div class="p3-side"><h4>3D-фигуры</h4><div class="p3-grid">${Object.keys(M3N).map(k=>`<button data-add="${k}"><b>${{cube:'▣',sphere:'●',cyl:'⬮',cone:'▲',torus:'◎',plane:'▭',pyramid:'◭'}[k]}</b>${M3N[k].split(' ')[0]}</button>`).join('')}</div><h4>Цвет</h4><div class="p3-col">${P3COL.map(c=>`<i data-c="${c}" style="background:${c}"></i>`).join('')}</div><div class="props"></div><small style="opacity:.7;line-height:1.6">Перетаскивайте фигуру мышью. Пустое место / ПКМ — вращать камеру, колесо — масштаб. Delete — удалить.</small></div></div></div>`);
 const win=WM.create({app:'paint3d',title:'Paint 3D',icon:AI.paint3d(),width:1060,height:680,content:root,minW:640,minH:420});root.tabIndex=0;
 const cv=$('canvas',root),S=scene3d(cv,{bg:['#f7f9fc','#dfe7f1'],grid:'rgba(0,0,0,.06)',orbitAny:true,selCol:'#0078d4'});const bgs=[['#f7f9fc','#dfe7f1'],['#1b1f3b','#53346d'],['#fff1e6','#ffd6a5'],['#d8f3dc','#74c69d'],'#ffffff'];let bgi=0;
 function demo(){S.objs=[];S.add('plane','#74c69d');Object.assign(S.objs[0],{p:[0,0,0],s:[4,1,4]});S.add('cube','#e74c3c');Object.assign(S.objs[1],{p:[-1.5,.8,0],s:[.8,.8,.8],r:[0,.6,0]});S.add('sphere','#4c9be8');Object.assign(S.objs[2],{p:[1.2,1,0],s:[1,1,1]});S.add('torus','#ff6fb5');Object.assign(S.objs[3],{p:[0,.4,1.8],s:[.7,.7,.7]});S.add('cone','#ffd60a');Object.assign(S.objs[4],{p:[-.3,.9,-1.8],s:[.6,.9,.6]});S.sel=-1;props();S.render();}
 function props(){const o=S.objs[S.sel];const pe=$('.props',root);if(!o){pe.innerHTML='';return;}pe.innerHTML=`<h4>${esc(o.name)}</h4><label>Размер<input type="range" min="0.2" max="4" step="0.05" value="${o.s[0]}" data-k="size"></label><label>Высота<input type="range" min="0.1" max="5" step="0.05" value="${o.p[1]}" data-k="y"></label><label>Поворот<input type="range" min="-3.14" max="3.14" step="0.02" value="${o.r[1]}" data-k="ry"></label><label>Наклон<input type="range" min="-3.14" max="3.14" step="0.02" value="${o.r[0]}" data-k="rx"></label><label>Материал<select data-k="mat"><option value="">Матовый</option><option value="metal" ${o.mat?'selected':''}>Глянец</option></select></label><button class="btn" data-a="dup">Дублировать</button> <button class="btn" data-a="del">Удалить</button>`;}
 root.addEventListener('input',e=>{const o=S.objs[S.sel],k=e.target.dataset.k;if(!o||!k)return;const v=+e.target.value;if(k==='size')o.s=[v,v,v];if(k==='y')o.p[1]=v;if(k==='ry')o.r[1]=v;if(k==='rx')o.r[0]=v;if(k==='mat')o.mat=e.target.value;S.render();});
 root.addEventListener('click',e=>{const t=e.target;if(t.dataset.add){S.add(t.closest('[data-add]').dataset.add);props();S.render();Sound.click();}const ad=t.closest('[data-add]');if(ad&&!t.dataset.add){S.add(ad.dataset.add);props();S.render();}
  if(t.dataset.c&&S.objs[S.sel]){S.objs[S.sel].c=t.dataset.c;S.render();}const a=t.closest('[data-a]')?.dataset.a;
  if(a==='bg'){bgi=(bgi+1)%bgs.length;S.bg=bgs[bgi];S.render();}if(a==='demo')demo();if(a==='clear'){S.objs=[];S.sel=-1;props();S.render();}
  if(a==='save'){S.sel=-1;S.render(true);savePng(cv,PICS,'Paint3D_'+Date.now()%100000+'.png','Paint 3D');S.render();}
  if(a==='del'&&S.sel>=0){S.objs.splice(S.sel,1);S.sel=-1;props();S.render();}if(a==='dup'&&S.sel>=0){const o=JSON.parse(JSON.stringify(S.objs[S.sel]));o.p[0]+=1.2;o.name+=' копия';S.objs.push(o);S.sel=S.objs.length-1;props();S.render();}});
 let mv=null;cv.addEventListener('pointerdown',e=>{if(e.button)return;const [px,py]=S.pos(e);const i=S.pick(px,py);if(i>=0){S.sel=i;props();mv={x:e.clientX,y:e.clientY};cv.setPointerCapture(e.pointerId);S.render();}},true);
 cv.addEventListener('pointermove',e=>{if(!mv)return;const o=S.objs[S.sel];const {right,fwd}=S.camVec();const dx=(e.clientX-mv.x)*S.cam.dist*.0016,dy=(e.clientY-mv.y)*S.cam.dist*.0016;o.p[0]+=right[0]*dx+fwd[0]*dy*-1*-1*0+fwd[0]*-dy*-1;o.p[2]+=right[2]*dx+fwd[2]*dy;mv={x:e.clientX,y:e.clientY};S.render();e.stopImmediatePropagation();},true);
 cv.addEventListener('pointerup',()=>mv=null,true);
 root.addEventListener('keydown',e=>{if(e.key==='Delete'&&S.sel>=0&&e.target.tagName!=='INPUT'){S.objs.splice(S.sel,1);S.sel=-1;props();S.render();}});
 fitCanvas(cv,()=>S.render());demo();return win;}});
alias('paint3d','paint3d','paint 3d','пейнт 3д');

/* ---------- Blender ---------- */
addCSS(`.bl{flex:1;display:flex;flex-direction:column;min-height:0;background:#303030;color:#ddd;font-size:12px}
.bl-top{display:flex;align-items:center;gap:2px;height:28px;padding:0 6px;background:#232323}.bl-top button{padding:3px 9px;border-radius:4px}.bl-top button:hover{background:#3d3d3d}.bl-top .ws{background:#4772b3;color:#fff}
.bl-b{flex:1;display:flex;min-height:0}.bl-tools{width:38px;background:#2b2b2b;display:flex;flex-direction:column;gap:3px;padding:6px 3px}.bl-tools button{height:30px;border-radius:4px;font-size:14px}.bl-tools button.on{background:#4772b3}
.bl-vp{flex:1;position:relative}.bl-vp canvas{position:absolute;inset:0;width:100%;height:100%}.bl-hud{position:absolute;left:8px;top:6px;color:#bbb;pointer-events:none;line-height:1.5}
.bl-menu{position:absolute;background:#1d1d1d;border:1px solid #444;border-radius:5px;padding:4px;z-index:5;min-width:150px}.bl-menu div{padding:4px 10px;border-radius:3px;cursor:default}.bl-menu div:hover{background:#4772b3}
.bl-right{width:250px;display:flex;flex-direction:column;background:#2b2b2b;border-left:1px solid #1d1d1d}.bl-out{height:40%;overflow:auto;border-bottom:1px solid #1d1d1d}.bl-out div{padding:3px 10px;cursor:default}.bl-out div.on{background:#334d80}
.bl-props{flex:1;overflow:auto;padding:8px}.bl-props h5{margin:6px 0;color:#aaa;font-size:11px;text-transform:uppercase}.bl-props .row{display:grid;grid-template-columns:70px 1fr 1fr 1fr;gap:3px;margin-bottom:4px;align-items:center}
.bl-props input{width:100%;background:#545454;border:0;border-radius:3px;color:#fff;padding:3px 4px;font-size:11px}.bl-status{height:22px;display:flex;align-items:center;gap:14px;padding:0 10px;background:#232323;color:#999}`);
storeApp('blender',{cat:'creative',dev:'Blender Foundation',rating:4.9,size:'340 МБ',desc:'Свободный 3D-пакет (упрощённый): горячие клавиши G/R/S/X, Shift+A, обозреватель, рендер F12 и экспорт .obj.',feat:['G — перемещение, R — поворот, S — масштаб','F12 — рендер в PNG','Экспорт сцены в Wavefront .obj']},{name:'Blender',icon:AI.blender,keywords:'blender блендер 3d моделирование',launch(){
 const root=el(`<div class="bl" tabindex="0"><div class="bl-top"><button>Файл</button><button>Правка</button><button data-a="render">Рендер</button><button>Окно</button><button class="ws">Layout</button><button>Modeling</button><button>Shading</button><span style="flex:1"></span><button data-a="obj">Экспорт .obj</button></div><div class="bl-b"><div class="bl-tools"><button class="on" title="Выделение">↖</button><button data-k="g" title="Переместить (G)">✥</button><button data-k="r" title="Повернуть (R)">⟳</button><button data-k="s" title="Масштаб (S)">⤢</button></div><div class="bl-vp"><canvas></canvas><div class="bl-hud">Перспектива пользователя<br>(1) Collection</div></div><div class="bl-right"><div class="bl-out"></div><div class="bl-props"></div></div></div><div class="bl-status"><span class="st">ЛКМ — выбрать · СКМ/ПКМ — вращать · Shift+A — добавить · G/R/S · X — удалить · F12 — рендер</span><span style="margin-left:auto" class="cnt"></span><span>4.2.0</span></div></div>`);
 const win=WM.create({app:'blender',title:'Blender',icon:AI.blender(),width:1120,height:700,content:root,minW:700,minH:420,onFocus:()=>root.focus()});
 const cv=$('canvas',root),S=scene3d(cv,{bg:'#3d3d3d',grid:'rgba(255,255,255,.09)',wire:'rgba(0,0,0,.25)',selCol:'#ffa133'});
 S.add('cube','#bdbdbd');S.objs[0].p=[0,1,0];S.objs[0].name='Cube';S.sel=0;
 let mode=null,start=null,mouse=[0,0];
 function ui(){$('.bl-out',root).innerHTML='<div style="color:#aaa">📁 Scene Collection</div>'+S.objs.map((o,i)=>`<div data-i="${i}" class="${i===S.sel?'on':''}">&nbsp;&nbsp;▽ ${esc(o.name)}</div>`).join('')+'<div style="color:#888">&nbsp;&nbsp;📷 Camera</div><div style="color:#888">&nbsp;&nbsp;💡 Light</div>';
  const o=S.objs[S.sel];$('.bl-props',root).innerHTML=o?`<h5>Объект: ${esc(o.name)}</h5>${[['Положение','p'],['Вращение','r'],['Масштаб','s']].map(([n,k])=>`<div class="row"><span>${n}</span>${[0,1,2].map(j=>`<input data-k="${k}" data-j="${j}" value="${(k==='r'?o[k][j]*180/Math.PI:o[k][j]).toFixed(2)}">`).join('')}</div>`).join('')}<h5>Материал</h5><div class="row"><span>Цвет</span><input type="color" data-k="c" value="${o.c}" style="grid-column:span 3;height:24px;padding:0"></div>`:'<h5>Нет выделения</h5>';
  $('.cnt',root).textContent=`Объекты ${S.sel>=0?1:0}/${S.objs.length} · Вершины ${S.objs.reduce((s,o)=>s+M3C[o.type].v.length,0)}`;S.render();}
 root.addEventListener('change',e=>{const o=S.objs[S.sel],k=e.target.dataset.k;if(!o||!k)return;if(k==='c')o.c=e.target.value;else{const v=parseFloat(e.target.value)||0;o[k][+e.target.dataset.j]=k==='r'?v*Math.PI/180:v;}ui();});
 function addMenu(px,py){const m=el(`<div class="bl-menu" style="left:${px}px;top:${py}px"><div style="color:#888;pointer-events:none">Добавить ▸ Полисетка</div>${Object.keys(M3N).map(k=>`<div data-add="${k}">${M3N[k]}</div>`).join('')}</div>`);$('.bl-vp',root).appendChild(m);m.onclick=e=>{const k=e.target.dataset.add;if(k){S.add(k,'#bdbdbd');S.objs[S.sel].name=k[0].toUpperCase()+k.slice(1)+'.'+String(S.objs.length).padStart(3,'0');ui();}m.remove();};setTimeout(()=>document.addEventListener('pointerdown',function h(ev){if(!m.contains(ev.target)){m.remove();document.removeEventListener('pointerdown',h);}}),0);}
 function begin(k){if(S.sel<0)return;const o=S.objs[S.sel];mode=k;start={m:[...mouse],p:[...o.p],r:[...o.r],s:[...o.s]};$('.st',root).textContent={g:'Перемещение',r:'Вращение',s:'Масштаб'}[k]+' — двигайте мышь, ЛКМ/Enter — применить, ПКМ/Esc — отмена';}
 function finish(ok){if(!mode)return;const o=S.objs[S.sel];if(!ok){o.p=start.p;o.r=start.r;o.s=start.s;}mode=null;$('.st',root).textContent='Готово';ui();}
 cv.addEventListener('pointermove',e=>{const r=cv.getBoundingClientRect();mouse=[e.clientX-r.left,e.clientY-r.top];if(!mode)return;const o=S.objs[S.sel],dx=mouse[0]-start.m[0],dy=mouse[1]-start.m[1];
  if(mode==='g'){const {right}=S.camVec(),k=S.cam.dist*.0018;o.p=[start.p[0]+right[0]*dx*k,start.p[1]-dy*k,start.p[2]+right[2]*dx*k];}
  if(mode==='r')o.r=[start.r[0],start.r[1]+dx*.01,start.r[2]];if(mode==='s'){const f=Math.max(.05,1+dx*.006);o.s=start.s.map(v=>v*f);}S.render();});
 cv.addEventListener('pointerdown',e=>{if(mode){finish(e.button===0);e.stopImmediatePropagation();return;}if(e.button===0&&!e.altKey){const [px,py]=S.pos(e);S.sel=S.pick(px,py);ui();}},true);
 root.addEventListener('keydown',e=>{if(e.target.tagName==='INPUT')return;const k=e.key.toLowerCase();
  if(e.shiftKey&&k==='a'){e.preventDefault();addMenu(mouse[0],mouse[1]);return;}if(mode&&(k==='enter'))return finish(true);if(mode&&k==='escape')return finish(false);
  if(['g','r','s'].includes(k)&&!e.ctrlKey){e.preventDefault();begin(k);}if((k==='x'||k==='delete')&&S.sel>=0){S.objs.splice(S.sel,1);S.sel=-1;ui();}
  if(e.key==='F12'){e.preventDefault();render();}if(e.shiftKey&&k==='d'&&S.sel>=0){const o=JSON.parse(JSON.stringify(S.objs[S.sel]));o.name+='.dup';S.objs.push(o);S.sel=S.objs.length-1;ui();begin('g');}
  if(k==='a'&&!e.shiftKey){S.sel=S.sel>=0?-1:0;ui();}});
 root.addEventListener('click',e=>{const t=e.target.closest('[data-i],[data-a],[data-k]');if(!t)return;if(t.dataset.i){S.sel=+t.dataset.i;ui();}if(t.dataset.k)begin(t.dataset.k);if(t.dataset.a==='render')render();if(t.dataset.a==='obj'){if(!VFS.isDir(DOCS))VFS.mkdir(DOCS);const p=DOCS+'\\scene.obj';VFS.write(p,S.toObj());Shell.notify({title:'Blender',body:'Экспорт .obj: '+p,silent:true});Sound.pop();}});
 function render(){const c2=document.createElement('canvas');c2.width=960;c2.height=540;const R=scene3d(c2,{bg:['#55607a','#1d2230']});R.objs=S.objs;R.cam=S.cam;R.sel=-1;R.render(true);
  const body=el('<div style="flex:1;display:flex;flex-direction:column;background:#232323;color:#ddd"><div style="padding:6px 10px;font-size:12px;display:flex;gap:10px"><span>Blender Render — Кадр 1 | Время: 00:00.42 | Cycles (почти)</span><span style="flex:1"></span><button class="btn">Сохранить изображение</button></div><div style="flex:1;display:grid;place-items:center;min-height:0"></div></div>');c2.style.cssText='max-width:100%;max-height:100%';$('div:last-child',body).appendChild(c2);
  WM.create({app:'blender',title:'Рендер Blender',icon:AI.blender(),width:900,height:560,content:body});$('button',body).onclick=()=>savePng(c2,PICS,'render_'+Date.now()%100000+'.png','Blender');Sound.win();}
 fitCanvas(cv,()=>ui());ui();return win;}});
alias('blender','blender','блендер');

/* ============================ FL STUDIO ============================ */
addCSS(`.fl{flex:1;display:flex;flex-direction:column;min-height:0;background:#2d3439;color:#d6dde3;font-size:12px;user-select:none}
.fl-top{display:flex;align-items:center;gap:8px;padding:6px 10px;background:linear-gradient(#4a5258,#3a4146);border-bottom:1px solid #1d2125}
.fl-top button{padding:4px 10px;border-radius:3px;background:#262b2f;color:#e9eef2;border:1px solid #1a1d20}.fl-top button.on{background:#ff8c1a;color:#111}
.fl-lcd{font:600 16px var(--mono);color:#9cff57;background:#111;padding:3px 10px;border-radius:3px;min-width:110px;text-align:center}
.fl-top input[type=number]{width:56px;background:#111;color:#9cff57;border:0;border-radius:3px;padding:4px;font:600 14px var(--mono)}
.fl-main{flex:1;overflow:auto;padding:10px}.fl-rack{background:#383f45;border-radius:6px;padding:8px;box-shadow:0 2px 10px rgba(0,0,0,.4)}
.fl-row{display:flex;align-items:center;gap:6px;margin:3px 0}.fl-name{width:96px;padding:5px 8px;background:#4b545b;border-radius:3px;white-space:nowrap;overflow:hidden}.fl-row input[type=range]{width:60px}
.fl-st{width:24px;height:28px;border-radius:3px;background:#5b646b;cursor:pointer}.fl-st:nth-child(8n+3),.fl-st:nth-child(8n+4),.fl-st:nth-child(8n+5),.fl-st:nth-child(8n+6){background:#7a5a5a}
.fl-st.on{background:#ff8c1a!important;box-shadow:inset 0 0 6px #fff7}.fl-st.cur{outline:2px solid #9cff57}
.fl-pr{margin-top:12px;background:#22272b;border-radius:6px;padding:8px}.fl-pr h4{margin-bottom:6px;font-weight:600}
.fl-keys{display:grid;grid-template-columns:44px repeat(16,1fr);gap:1px}.fl-keys span{height:16px;background:#2f363b;cursor:pointer}.fl-keys span.k{background:#ddd;color:#111;font-size:9px;padding-left:3px;cursor:default}.fl-keys span.k.bk{background:#222;color:#ddd}.fl-keys span.on{background:#7cff4f}.fl-keys span.cur{background:#3d474e}`);
const FL_CH=[['Kick','#ff8c1a'],['Snare','#ff5c5c'],['Clap','#ffd166'],['Hi-Hat','#9cff57'],['Open Hat','#57ffd8'],['Bass 808','#57a6ff'],['Pluck','#c57bff'],['Pony FX 🦄','#ff7bd8']];
const FL_NOTES=['C5','B4','A#4','A4','G#4','G4','F#4','F4','E4','D#4','D4','C#4','C4'];
storeApp('fl',{cat:'creative',dev:'Image-Line',rating:4.8,size:'890 МБ',desc:'Создавай биты: пошаговый секвенсор на 8 каналов, синтез ударных, пианино-ролл, BPM и экспорт WAV.',feat:['Step sequencer 8×16','Piano roll для мелодии','Экспорт в настоящий .wav']},{name:'FL Studio',icon:AI.fl,keywords:'fl studio фл студио музыка биты daw секвенсор',launch(){
 const st=LS.get('flPat',null)||{bpm:128,steps:FL_CH.map((_,i)=>Array.from({length:16},(_,j)=>i===0?j%4===0:i===1?j%8===4:i===3?j%2===0:false)),vol:FL_CH.map(()=>.8),notes:{}};
 const root=el(`<div class="fl"><div class="fl-top"><b style="color:#ff8c1a;font-size:14px">FL STUDIO</b><button data-a="play">▶</button><button data-a="stop">■</button><span class="fl-lcd">1:01:000</span>BPM <input type="number" min="60" max="200" value="${st.bpm}"><button data-a="clear">Очистить</button><button data-a="rand">🎲 Случайный бит</button><span style="flex:1"></span><button data-a="wav">Экспорт WAV</button></div><div class="fl-main"><div class="fl-rack"></div><div class="fl-pr"><h4>🎹 Piano roll — Lead Synth</h4><div class="fl-keys"></div></div></div></div>`);
 const win=WM.create({app:'fl',title:'FL Studio',icon:AI.fl(),width:900,height:640,content:root,minW:700,minH:420});
 let ac=null,master,playing=false,step=0,tm=null;const save=()=>LS.set('flPat',st);
 const A=()=>{if(!ac){ac=new (window.AudioContext||window.webkitAudioContext)();master=ac.createGain();master.gain.value=.7;master.connect(ac.destination);}return ac;};
 function voice(ctx,out,ch,t,vol){const g=ctx.createGain();g.connect(out);const o=(type,f)=>{const n=ctx.createOscillator();n.type=type;n.frequency.value=f;return n;};const noise=d=>{const b=ctx.createBuffer(1,ctx.sampleRate*d,ctx.sampleRate),a=b.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=Math.random()*2-1;const s=ctx.createBufferSource();s.buffer=b;return s;};
  if(ch===0){const n=o('sine',150);n.frequency.exponentialRampToValueAtTime(40,t+.15);g.gain.setValueAtTime(vol,t);g.gain.exponentialRampToValueAtTime(.001,t+.4);n.connect(g);n.start(t);n.stop(t+.4);}
  else if(ch===1||ch===2){const s=noise(.3),f=ctx.createBiquadFilter();f.type='bandpass';f.frequency.value=ch===1?1800:1200;s.connect(f);f.connect(g);g.gain.setValueAtTime(vol*(ch===2?.9:.8),t);g.gain.exponentialRampToValueAtTime(.001,t+(ch===1?.2:.15));s.start(t);if(ch===1){const n=o('triangle',190);const g2=ctx.createGain();g2.gain.setValueAtTime(vol*.5,t);g2.gain.exponentialRampToValueAtTime(.001,t+.1);n.connect(g2);g2.connect(out);n.start(t);n.stop(t+.1);}}
  else if(ch===3||ch===4){const s=noise(.3),f=ctx.createBiquadFilter();f.type='highpass';f.frequency.value=7000;s.connect(f);f.connect(g);g.gain.setValueAtTime(vol*.45,t);g.gain.exponentialRampToValueAtTime(.001,t+(ch===3?.05:.25));s.start(t);}
  else if(ch===5){const n=o('sine',55);g.gain.setValueAtTime(vol,t);g.gain.exponentialRampToValueAtTime(.001,t+.6);n.frequency.setValueAtTime(70,t);n.frequency.exponentialRampToValueAtTime(48,t+.3);n.connect(g);n.start(t);n.stop(t+.6);}
  else if(ch===6){const f=[262,330,392,523][Math.random()*4|0];const n=o('sawtooth',f),fl=ctx.createBiquadFilter();fl.type='lowpass';fl.frequency.setValueAtTime(3000,t);fl.frequency.exponentialRampToValueAtTime(300,t+.25);n.connect(fl);fl.connect(g);g.gain.setValueAtTime(vol*.3,t);g.gain.exponentialRampToValueAtTime(.001,t+.3);n.start(t);n.stop(t+.3);}
  else if(ch===7){const n=o('square',880);n.frequency.exponentialRampToValueAtTime(1760,t+.08);n.frequency.exponentialRampToValueAtTime(440,t+.2);n.connect(g);g.gain.setValueAtTime(vol*.2,t);g.gain.exponentialRampToValueAtTime(.001,t+.22);n.start(t);n.stop(t+.22);}}
 function lead(ctx,out,ni,t,len){const f=440*Math.pow(2,(['C4','C#4','D4','D#4','E4','F4','F#4','G4','G#4','A4','A#4','B4','C5'].indexOf(FL_NOTES[ni])-9)/12);const g=ctx.createGain();g.connect(out);[0,7].forEach(dt=>{const n=ctx.createOscillator();n.type='sawtooth';n.frequency.value=f;n.detune.value=dt;const fl=ctx.createBiquadFilter();fl.type='lowpass';fl.frequency.value=2200;n.connect(fl);fl.connect(g);n.start(t);n.stop(t+len);});g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.12,t+.01);g.gain.setValueAtTime(.12,t+len*.7);g.gain.linearRampToValueAtTime(0,t+len);}
 function playStep(ctx,out,s,t){const len=60/st.bpm/4;st.steps.forEach((r,ch)=>{if(r[s])voice(ctx,out,ch,t,st.vol[ch]);});FL_NOTES.forEach((_,ni)=>{if(st.notes[ni+':'+s])lead(ctx,out,ni,t,len*.95);});}
 function rack(){$('.fl-rack',root).innerHTML=FL_CH.map(([n,c],i)=>`<div class="fl-row"><input type="range" min="0" max="1" step="0.05" value="${st.vol[i]}" data-v="${i}" title="Громкость"><div class="fl-name" style="border-left:4px solid ${c}" data-prev="${i}">${n}</div>${st.steps[i].map((on,j)=>`<div class="fl-st${on?' on':''}" data-s="${i}:${j}"></div>`).join('')}</div>`).join('');
  $('.fl-keys',root).innerHTML=FL_NOTES.map((n,ni)=>`<span class="k${n.includes('#')?' bk':''}">${n}</span>`+Array.from({length:16},(_,j)=>`<span data-n="${ni}:${j}" class="${st.notes[ni+':'+j]?'on':''}"></span>`).join('')).join('');}
 function tick(){if(!playing)return;const ctx=A();$$('.fl-st.cur,.fl-keys .cur',root).forEach(x=>x.classList.remove('cur'));$$(`.fl-st[data-s$=":${step}"]`,root).forEach(x=>x.classList.add('cur'));
  playStep(ctx,master,step,ctx.currentTime+.02);$('.fl-lcd',root).textContent=`1:${String((step/4|0)+1).padStart(2,'0')}:${String((step%4)*24).padStart(3,'0')}`;step=(step+1)%16;tm=setTimeout(tick,60000/st.bpm/4);}
 root.addEventListener('click',e=>{const t=e.target;if(t.dataset.s){const [i,j]=t.dataset.s.split(':').map(Number);st.steps[i][j]=!st.steps[i][j];t.classList.toggle('on');if(st.steps[i][j]){const c=A();voice(c,master,i,c.currentTime,st.vol[i]);}save();}
  if(t.dataset.n){st.notes[t.dataset.n]=!st.notes[t.dataset.n];if(!st.notes[t.dataset.n])delete st.notes[t.dataset.n];t.classList.toggle('on');if(st.notes[t.dataset.n]){const c=A();lead(c,master,+t.dataset.n.split(':')[0],c.currentTime,.2);}save();}
  if(t.dataset.prev){const c=A();voice(c,master,+t.dataset.prev,c.currentTime,st.vol[+t.dataset.prev]);}
  const a=t.closest('[data-a]')?.dataset.a;if(a==='play'){if(!playing){playing=true;A().resume();t.classList.add('on');tick();}}if(a==='stop'){playing=false;clearTimeout(tm);step=0;$('[data-a=play]',root).classList.remove('on');$$('.cur',root).forEach(x=>x.classList.remove('cur'));}
  if(a==='clear'){st.steps=st.steps.map(r=>r.map(()=>false));st.notes={};rack();save();}if(a==='rand'){st.steps=st.steps.map((r,i)=>r.map((_,j)=>i===0?j%4===0||Math.random()<.1:i===1?j%8===4:Math.random()<[0,0,.15,.5,.1,.2,.25,.06][i]));rack();save();}
  if(a==='wav')exportWav();});
 root.addEventListener('input',e=>{if(e.target.dataset.v){st.vol[+e.target.dataset.v]=+e.target.value;save();}if(e.target.type==='number'){st.bpm=Math.max(60,Math.min(200,+e.target.value||128));save();}});
 async function exportWav(){const len=60/st.bpm/4,bars=2,sr=44100,dur=16*len*bars+1;const ctx=new OfflineAudioContext(2,sr*dur,sr);const out=ctx.createGain();out.gain.value=.7;out.connect(ctx.destination);for(let b=0;b<bars;b++)for(let s=0;s<16;s++)playStep(ctx,out,s,(b*16+s)*len);
  const buf=await ctx.startRendering();const n=buf.length,dv=new DataView(new ArrayBuffer(44+n*4));const ws=(o,s)=>[...s].forEach((ch,i)=>dv.setUint8(o+i,ch.charCodeAt(0)));ws(0,'RIFF');dv.setUint32(4,36+n*4,true);ws(8,'WAVEfmt ');dv.setUint32(16,16,true);dv.setUint16(20,1,true);dv.setUint16(22,2,true);dv.setUint32(24,sr,true);dv.setUint32(28,sr*4,true);dv.setUint16(32,4,true);dv.setUint16(34,16,true);ws(36,'data');dv.setUint32(40,n*4,true);
  const L=buf.getChannelData(0),R=buf.getChannelData(1);for(let i=0;i<n;i++){dv.setInt16(44+i*4,Math.max(-1,Math.min(1,L[i]))*32767,true);dv.setInt16(46+i*4,Math.max(-1,Math.min(1,R[i]))*32767,true);}
  const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([dv],{type:'audio/wav'}));a.download='beat.wav';document.body.appendChild(a);a.click();a.remove();Shell.notify({title:'FL Studio',body:'Бит экспортирован в beat.wav (загрузка в настоящий браузер)',silent:true});}
 win.onClose=()=>{playing=false;clearTimeout(tm);ac&&ac.close();};rack();return win;}});
alias('fl','fl','fl studio','фл студио','fruityloops');

/* ============================ ФОТОРЕДАКТОР ============================ */
addCSS(`.ph{flex:1;display:flex;min-height:0;background:#1f1f1f;color:#ddd;font-size:12px}.ph-side{width:240px;background:#2a2a2a;padding:12px;overflow:auto;display:flex;flex-direction:column;gap:8px}
.ph-side label{display:flex;flex-direction:column;gap:3px}.ph-side h4{font-size:12px;text-transform:uppercase;color:#31a8ff;margin-top:6px}.ph-side .row{display:flex;flex-wrap:wrap;gap:4px}.ph-side button{padding:5px 8px;border-radius:4px;background:#3a3a3a;color:#eee}.ph-side button:hover{background:#4a4a4a}
.ph-vp{flex:1;display:grid;place-items:center;overflow:auto;background:repeating-conic-gradient(#2b2b2b 0 25%,#333 0 50%) 0 0/20px 20px}.ph-vp canvas{max-width:95%;max-height:95%;box-shadow:0 4px 20px rgba(0,0,0,.6)}`);
storeApp('photo',{cat:'creative',dev:'Pixel Pony Inc.',rating:4.5,size:'120 МБ',desc:'Фоторедактор в стиле Photoshop: яркость, контраст, насыщенность, фильтры, поворот, текст и мем-режим. Открывает файлы и с вашего настоящего ПК.',feat:['Коррекция цвета','Фильтры: Ч/Б, сепия, негатив, размытие','Текст как в мемах']},{name:'Фоторедактор',icon:AI.photo,keywords:'photo editor photoshop фотошоп фоторедактор фильтры',launch(o={}){
 const F={brightness:100,contrast:100,saturate:100,hue:0,blur:0,grayscale:0,sepia:0,invert:0};
 const root=el(`<div class="ph"><div class="ph-side"><div class="row"><button data-a="open">📂 Открыть с ПК</button><button data-a="demo">🌅 Пример</button></div><h4>Коррекция</h4>${[['brightness','Яркость',0,200],['contrast','Контраст',0,200],['saturate','Насыщенность',0,300],['hue','Цветовой тон',-180,180],['blur','Размытие',0,10]].map(([k,n,a,b])=>`<label>${n}<input type="range" data-f="${k}" min="${a}" max="${b}" value="${F[k]}"></label>`).join('')}<h4>Фильтры</h4><div class="row"><button data-p="none">Оригинал</button><button data-p="bw">Ч/Б</button><button data-p="sepia">Сепия</button><button data-p="invert">Негатив</button><button data-p="vivid">Ярко</button><button data-p="cyber">Киберпанк</button></div><h4>Трансформация</h4><div class="row"><button data-a="rot">⟳ 90°</button><button data-a="flip">⇆ Отразить</button></div><h4>Текст (мем)</h4><input class="inp" data-t="top" placeholder="Верхний текст"><input class="inp" data-t="bot" placeholder="Нижний текст"><h4>Экспорт</h4><div class="row"><button data-a="save">💾 В «Изображения»</button><button data-a="dl">⬇ Скачать на ПК</button></div></div><div class="ph-vp"><canvas></canvas></div></div>`);
 const win=WM.create({app:'photo',title:'Фоторедактор',icon:AI.photo(),width:1040,height:680,content:root,minW:640,minH:420});
 const cv=$('canvas',root),x=cv.getContext('2d');let img=null,rot=0,flip=1,txt={top:'',bot:''};
 function demoImg(){const c=document.createElement('canvas');c.width=900;c.height=600;const g=c.getContext('2d');const gr=g.createLinearGradient(0,0,0,600);gr.addColorStop(0,'#ff9a8b');gr.addColorStop(.5,'#ff6a88');gr.addColorStop(1,'#2a1b5c');g.fillStyle=gr;g.fillRect(0,0,900,600);g.fillStyle='#ffe29f';g.beginPath();g.arc(450,330,110,0,7);g.fill();g.fillStyle='#1b1035';for(let i=0;i<9;i++){g.beginPath();g.moveTo(i*120-80,600);g.lineTo(i*120,380+(i%3)*40);g.lineTo(i*120+90,600);g.fill();}g.fillStyle='#fff';g.font='bold 30px sans-serif';g.fillText('Windows11WEB',30,50);return c;}
 function load(src){const im=new Image();im.onload=()=>{img=im;draw();};im.src=src;}
 function draw(){if(!img)return;const w=rot%180?img.height:img.width,h=rot%180?img.width:img.height;cv.width=w;cv.height=h;x.save();x.filter=`brightness(${F.brightness}%) contrast(${F.contrast}%) saturate(${F.saturate}%) hue-rotate(${F.hue}deg) blur(${F.blur}px) grayscale(${F.grayscale}%) sepia(${F.sepia}%) invert(${F.invert}%)`;
  x.translate(w/2,h/2);x.rotate(rot*Math.PI/180);x.scale(flip,1);x.drawImage(img,-img.width/2,-img.height/2);x.restore();
  const fs=Math.max(24,w/12);x.font=`900 ${fs}px Impact, Arial Black, sans-serif`;x.textAlign='center';x.lineWidth=fs/12;x.strokeStyle='#000';x.fillStyle='#fff';
  if(txt.top){x.strokeText(txt.top.toUpperCase(),w/2,fs*1.1);x.fillText(txt.top.toUpperCase(),w/2,fs*1.1);}if(txt.bot){x.strokeText(txt.bot.toUpperCase(),w/2,h-fs*.35);x.fillText(txt.bot.toUpperCase(),w/2,h-fs*.35);}}
 root.addEventListener('input',e=>{const f=e.target.dataset.f;if(f){F[f]=+e.target.value;draw();}const t=e.target.dataset.t;if(t){txt[t]=e.target.value;draw();}});
 const presets={none:{grayscale:0,sepia:0,invert:0,saturate:100,hue:0,contrast:100,brightness:100,blur:0},bw:{grayscale:100,sepia:0,invert:0},sepia:{sepia:90,grayscale:0},invert:{invert:100},vivid:{saturate:180,contrast:115},cyber:{hue:-60,saturate:200,contrast:130}};
 root.addEventListener('click',e=>{const t=e.target;if(t.dataset.p){Object.assign(F,presets[t.dataset.p]);$$('[data-f]',root).forEach(i=>i.value=F[i.dataset.f]);draw();}const a=t.dataset.a;
  if(a==='open'){const inp=document.createElement('input');inp.type='file';inp.accept='image/*';inp.onchange=()=>{const f=inp.files[0];if(!f)return;const r=new FileReader();r.onload=()=>load(r.result);r.readAsDataURL(f);};inp.click();}
  if(a==='demo'){img=demoImg();draw();}if(a==='rot'){rot=(rot+90)%360;draw();}if(a==='flip'){flip*=-1;draw();}
  if(a==='save')savePng(cv,PICS,'photo_'+Date.now()%100000+'.png','Фоторедактор');
  if(a==='dl'){const l=document.createElement('a');l.href=cv.toDataURL('image/png');l.download='photo.png';document.body.appendChild(l);l.click();l.remove();}});
 if(o.path){const d=VFS.read(o.path);if(d&&d.startsWith('data:'))load(d);else{img=demoImg();draw();}}else{img=demoImg();draw();}return win;}});
alias('photo','photo','photoshop','фотошоп','фоторедактор');

/* ---------- v2 migration ---------- */
try{if(LS.get('ver',0)<2){const p='C:\\Users\\User\\Desktop\\Привет.txt';VFS.write(p,HELLO_TXT);LS.set('ver',2);}}catch(e){console.warn(e);}
