
/* ============================ TASK MANAGER ============================ */
const BG_PROCS=[{exe:'System',name:'System',crit:1,mem:0.1},{exe:'csrss.exe',name:'Процесс исполнения клиент-сервер',crit:1,mem:1.2},{exe:'explorer.exe',name:'Проводник Windows',shell:1,mem:58},{exe:'dwm.exe',name:'Диспетчер окон рабочего стола',mem:72},{exe:'svchost.exe',name:'Узел службы: Локальная система',mem:24},{exe:'svchost.exe',name:'Узел службы: Сетевая служба',mem:11},{exe:'SearchHost.exe',name:'Поиск',mem:46},{exe:'MsMpEng.exe',name:'Antimalware Service Executable',mem:180},{exe:'audiodg.exe',name:'Изоляция графов аудиоустройств',mem:9},{exe:'Widgets.exe',name:'Виджеты Windows',mem:33}].map((p,i)=>({...p,pid:[4,612,4312,1180,904,1340,6120,3388,7764,8020][i]}));
const KILLED=new Map();const EXE={explorer:'explorer.exe',terminal:'WindowsTerminal.exe',notepad:'Notepad.exe',paint:'mspaint.exe',minesweeper:'Minesweeper.exe',solitaire:'Solitaire.exe',taskmgr:'Taskmgr.exe',calc:'CalculatorApp.exe',settings:'SystemSettings.exe',viewer:'Photos.exe',run:'rundll32.exe',winver:'winver.exe'};
const _pidOf=new WeakMap();let _pidSeq=9000;
function TM_PROCS(){const now=Date.now();const out=[];WM.all().forEach(w=>{if(!_pidOf.has(w))_pidOf.set(w,_pidSeq+=4+Math.random()*40|0);const pid=_pidOf.get(w);const seed=(pid%97)/97;
  out.push({pid,win:w,exe:EXE[w.app]||w.app+'.exe',name:w.title,app:true,icon:w.icon,status:w.minimized?'Приостановлено':'',cpu:w.minimized?0:Math.max(0,Monitor.cpu*(.05+seed*.15)+Math.random()*1.2),mem:20+seed*120+(w.app==='paint'?60:0),disk:Math.random()<.2?Math.random()*.4:0,net:0});});
 BG_PROCS.forEach(p=>{if(KILLED.has(p.pid)&&KILLED.get(p.pid)>now)return;out.push({...p,app:false,icon:AI.pc(),status:'',cpu:Math.random()*Monitor.cpu*.04,mem:p.mem*(0.95+Math.random()*.1),disk:Math.random()<.1?Math.random()*.2:0,net:Math.random()<.2?Math.random()*.1:0});});return out;}
Apps.register('taskmgr',{name:'Диспетчер задач',icon:AI.taskmgr,single:true,keywords:'task manager taskmgr процессы',launch(){
 const root=el(`<div style="display:flex;flex:1;min-height:0"><div class="tm-side"><div class="si" data-a="menu"><span class="ico">${I.menu}</span><span>Диспетчер задач</span></div><div class="si on" data-p="procs"><span class="ico">${I.procs}</span><span>Процессы</span></div><div class="si" data-p="perf"><span class="ico">${I.perf}</span><span>Производительность</span></div></div><div class="tm-main"></div></div>`);
 const win=WM.create({app:'taskmgr',title:'Диспетчер задач',icon:AI.taskmgr(),width:860,height:580,content:root,minW:560,minH:380,onClose:()=>{alive=false;cancelAnimationFrame(raf);}});
 const main=$('.tm-main',root);let page='procs',selPid=null,alive=true,raf=0,metric='cpu',lastTick=performance.now();
 const MET={cpu:{n:'ЦП',full:'ЦП',sub:'Virtual Web CPU @ 3.60 ГГц',col:'#4cc2ff',fmt:v=>Math.round(v)+'%'},ram:{n:'Память',full:'Память',sub:'16,0 ГБ DDR5',col:'#c56cf0',fmt:v=>(v/100*16).toFixed(1)+'/16,0 ГБ ('+Math.round(v)+'%)'},disk:{n:'Диск 0 (C:)',full:'Диск 0 (C:)',sub:'Web Storage SSD',col:'#4caf50',fmt:v=>Math.round(v)+'%'},net:{n:'Ethernet',full:'Ethernet',sub:'Virtual Adapter',col:'#ff9f43',fmt:v=>'О: '+(v*0.12).toFixed(1)+' Мбит/с'}};
 function rProcs(){main.innerHTML=`<div class="tm-head"><span>Процессы</span><div style="display:flex;gap:6px"><button class="btn" data-a="newtask"><span class="ico" style="width:14px;height:14px">${I.run}</span> Запустить новую задачу</button><button class="btn primary" data-a="kill" disabled>Снять задачу</button></div></div><div class="tm-table"><table><thead><tr><th>Имя</th><th>Состояние</th><th class="num">ЦП<br><b class="tc"></b></th><th class="num">Память<br><b class="tr"></b></th><th class="num">Диск</th><th class="num">Сеть</th></tr></thead><tbody></tbody></table></div>`;fillProcs();}
 function fillProcs(){const tb=$('tbody',main);if(!tb)return;const L=TM_PROCS();const apps=L.filter(p=>p.app),bg=L.filter(p=>!p.app);$('.tc',main).textContent=Math.round(Monitor.cpu)+'%';$('.tr',main).textContent=Math.round(Monitor.ram)+'%';
  const row=p=>`<tr class="r${p.pid===selPid?' sel':''}" data-pid="${p.pid}"><td><div class="nm"><span class="ic">${p.icon}</span>${esc(p.app?(Apps.get(p.win.app)?.name||p.name):p.name)}${p.app&&p.name!==Apps.get(p.win.app)?.name?` <span class="muted">(${esc(p.name)})</span>`:''}</div></td><td class="muted">${p.status}</td><td class="num">${p.cpu.toFixed(1)}%</td><td class="num">${p.mem.toFixed(1)} МБ</td><td class="num">${p.disk.toFixed(1)} МБ/с</td><td class="num">${p.net.toFixed(1)} Мбит/с</td></tr>`;
  tb.innerHTML=`<tr><td colspan="6" style="font-weight:600;padding-top:12px">Приложения (${apps.length})</td></tr>${apps.map(row).join('')}<tr><td colspan="6" style="font-weight:600;padding-top:12px">Фоновые процессы (${bg.length})</td></tr>${bg.map(row).join('')}`;
  const k=$('[data-a=kill]',main);if(k)k.disabled=!L.some(p=>p.pid===selPid);}
 async function kill(){const p=TM_PROCS().find(x=>x.pid===selPid);if(!p)return;
  if(p.crit){if(!await Shell.confirm('Диспетчер задач',`Завершить процесс «${p.exe}»? Это системный процесс — Windows станет нестабильной или завершит работу.`))return;return Shell.bsod('CRITICAL_PROCESS_DIED');}
  if(p.app){p.win.onClose=null;WM.close(p.win);}
  else if(p.shell){KILLED.set(p.pid,Date.now()+3000);document.body.classList.add('noexplorer');$('#taskbar')?.classList.add('gone');$('#desktop')?.classList.add('gone');Shell.closePanels();
   setTimeout(()=>{document.body.classList.remove('noexplorer');$('#taskbar')?.classList.remove('gone');$('#desktop')?.classList.remove('gone');Shell.renderTaskbar();Shell.renderDesktop();},3000);}
  else KILLED.set(p.pid,Date.now()+12000);selPid=null;Sound.pop();fillProcs();}
 function rPerf(){main.innerHTML=`<div class="tm-head"><span>Производительность</span></div><div class="tm-perf"><div class="tm-plist">${Object.entries(MET).map(([k,m])=>`<div class="tm-pi${k===metric?' on':''}" data-m="${k}"><canvas width="140" height="88"></canvas><div><b>${m.n}</b><small class="v"></small></div></div>`).join('')}</div><div class="tm-pview"><h2><span class="t"></span><small class="s"></small></h2><div class="muted" style="font-size:12px;display:flex;justify-content:space-between"><span class="yl"></span><span>100%</span></div><canvas class="big"></canvas><div class="muted" style="font-size:12px;display:flex;justify-content:space-between;margin-bottom:12px"><span>60 секунд</span><span>0</span></div><div class="tm-stats"></div></div></div>`;stats();}
 function stats(){const m=MET[metric];const t=$('.tm-pview .t',main);if(!t)return;t.textContent=m.full;$('.tm-pview .s',main).textContent=m.sub;$('.yl',main).textContent=metric==='cpu'?'% использования':metric==='ram'?'Использование памяти':metric==='disk'?'Активность':'Пропускная способность';
  const L=TM_PROCS(),up=Math.floor((Date.now()-BOOT_TIME)/1000);const S={cpu:[['Использование',Math.round(Monitor.cpu)+'%'],['Скорость',(2.4+Monitor.cpu/100*2.2).toFixed(2)+' ГГц'],['Процессы',L.length],['Потоки',L.length*14+812],['Дескрипторы',L.length*310+24000],['Время работы',`${Math.floor(up/3600)}:${pad(Math.floor(up/60)%60)}:${pad(up%60)}`],['Ядра',navigator.hardwareConcurrency||4],['Виртуализация','Включено']],
   ram:[['Используется',(Monitor.ram/100*16).toFixed(1)+' ГБ'],['Доступно',(16-Monitor.ram/100*16).toFixed(1)+' ГБ'],['Выделено',(Monitor.ram/100*19).toFixed(1)+'/22,0 ГБ'],['Кэшировано','3,2 ГБ'],['Скорость','5600 МТ/с'],['Слотов','2 из 4']],
   disk:[['Активность',Math.round(Monitor.disk)+'%'],['Занято VFS',fmtSize(usedBytes())],['Емкость','5 МБ'],['Тип','localStorage']],net:[['Отправка',(Monitor.net*.04).toFixed(1)+' Мбит/с'],['Получение',(Monitor.net*.12).toFixed(1)+' Мбит/с'],['Состояние',Settings.get('wifi')?'Подключено':'Отключено'],['IPv4','192.168.1.11']]};
  $('.tm-stats',main).innerHTML=S[metric].map(([a,b])=>`<div><span class="muted">${a}</span><b>${b}</b></div>`).join('');$$('.tm-pi',main).forEach(p=>$('.v',p).textContent=MET[p.dataset.m].fmt(Monitor[p.dataset.m]));}
 function graph(cv,data,col,frac,grid){const dpr=devicePixelRatio||1;const w=cv.clientWidth*dpr|0,h=cv.clientHeight*dpr|0;if(!w||!h)return;if(cv.width!==w||cv.height!==h){cv.width=w;cv.height=h;}const x=cv.getContext('2d');x.clearRect(0,0,w,h);
  const N=60,step=w/(N-1),off=frac*step;if(grid){x.strokeStyle=col+'33';x.lineWidth=1;for(let i=1;i<10;i++){const y=h*i/10|0;x.beginPath();x.moveTo(0,y+.5);x.lineTo(w,y+.5);x.stroke();}const gs=w/20;const go=(Date.now()/1000%3)/3*gs*3%gs;for(let gx=w-go;gx>0;gx-=gs){x.beginPath();x.moveTo(gx+.5,0);x.lineTo(gx+.5,h);x.stroke();}}
  const d=data.slice(-N-1);if(d.length<2)return;x.beginPath();d.forEach((v,i)=>{const px=w-(d.length-1-i)*step-off+step,py=h-clamp(v,0,100)/100*h;if(!i)x.moveTo(px,py);else{const pv=d[i-1],ppx=px-step,ppy=h-clamp(pv,0,100)/100*h;x.bezierCurveTo(ppx+step/2,ppy,px-step/2,py,px,py);}});
  x.strokeStyle=col;x.lineWidth=1.5*dpr;x.stroke();x.lineTo(w,h);x.lineTo(w-(d.length-1)*step-off+step,h);x.closePath();const gr=x.createLinearGradient(0,0,0,h);gr.addColorStop(0,col+'66');gr.addColorStop(1,col+'11');x.fillStyle=gr;x.fill();}
 const loop=()=>{if(!alive)return;if(page==='perf'&&!win.minimized){const frac=clamp((performance.now()-lastTick)/1000,0,1);const big=$('.big',main);if(big)graph(big,Monitor.hist[metric],MET[metric].col,frac,true);$$('.tm-pi',main).forEach(p=>graph($('canvas',p),Monitor.hist[p.dataset.m],MET[p.dataset.m].col,frac,false));}raf=requestAnimationFrame(loop);};
 Bus.on('monitor',()=>{if(!alive)return;lastTick=performance.now();if(page==='procs')fillProcs();else stats();});
 Bus.on('windows',()=>{if(alive&&page==='procs')fillProcs();});
 root.addEventListener('click',e=>{const s=e.target.closest('.si');if(s){if(s.dataset.a==='menu')$('.tm-side',root).classList.toggle('wide');else{page=s.dataset.p;$$('.tm-side .si[data-p]',root).forEach(x=>x.classList.toggle('on',x===s));page==='procs'?rProcs():rPerf();}return;}
  const r=e.target.closest('tr.r');if(r){selPid=+r.dataset.pid;fillProcs();}const pi=e.target.closest('.tm-pi');if(pi){metric=pi.dataset.m;$$('.tm-pi',main).forEach(x=>x.classList.toggle('on',x===pi));stats();}
  const a=e.target.closest('[data-a]')?.dataset.a;if(a==='kill')kill();if(a==='newtask')Apps.launch('run');});
 root.addEventListener('dblclick',e=>{const r=e.target.closest('tr.r');if(r){const p=TM_PROCS().find(x=>x.pid===+r.dataset.pid);if(p&&p.win)WM.focus(p.win);}});
 root.addEventListener('contextmenu',e=>{const r=e.target.closest('tr.r');if(!r)return;e.preventDefault();e.stopPropagation();selPid=+r.dataset.pid;fillProcs();const p=TM_PROCS().find(x=>x.pid===selPid);
  Shell.menu(e.clientX,e.clientY,[...(p&&p.win?[{label:'Переключиться',icon:I.open,action:()=>WM.focus(p.win)}]:[]),{label:'Снять задачу',icon:I.close,key:'Del',action:kill}]);});
 root.tabIndex=0;root.addEventListener('keydown',e=>{if(e.key==='Delete'&&selPid)kill();});
 rProcs();loop();return win;}});

/* ============================ CALCULATOR ============================ */
Apps.register('calc',{name:'Калькулятор',icon:AI.calc,keywords:'calculator calc калькулятор счёт',launch(){
 const root=el(`<div class="calc"><div class="calc-main"><div class="calc-top"><button class="tbtn" data-a="mode" title="Режим"><span class="ico">${I.menu}</span></button><span class="mn">Обычный</span><span style="flex:1"></span><button class="tbtn" data-a="deg" style="font-size:12px;display:none">DEG</button><button class="tbtn" data-a="hist" title="Журнал"><span class="ico">${I.history}</span></button></div><div class="calc-disp"><span class="ex"></span><div class="rs">0</div></div><div class="calc-keys"></div></div><div class="calc-hist"><div style="font-weight:600;margin-bottom:8px">Журнал</div><div class="list"></div><button class="tbtn" data-a="clrh" style="align-self:flex-end" title="Очистить журнал"><span class="ico">${I.trash}</span></button></div></div>`);
 const win=WM.create({app:'calc',title:'Калькулятор',icon:AI.calc(),width:600,height:560,content:root,minW:330,minH:480,onResize:()=>histVis()});
 let sci=LS.get('calcSci',false),deg=true,expr='',entry='0',fresh=true,hist=LS.get('calcHist',[]),showHist=true,parens=0;
 const STD=[['%','pct','fn'],['CE','ce','fn'],['C','c','fn'],['⌫','bs','fn'],['¹/ₓ','inv','fn'],['x²','sq','fn'],['²√x','sqrt','fn'],['÷','/','op'],['7','7'],['8','8'],['9','9'],['×','*','op'],['4','4'],['5','5'],['6','6'],['−','-','op'],['1','1'],['2','2'],['3','3'],['+','+','op'],['+/−','neg'],['0','0'],[',','.'],['=','=','eq']];
 const SCI=[['sin','sin','fn'],['cos','cos','fn'],['tan','tan','fn'],['π','pi','fn'],['e','e','fn'],['ln','ln','fn'],['log','log','fn'],['n!','fact','fn'],['xʸ','^','op'],['10ˣ','p10','fn'],['(','(','fn'],[')',')','fn'],['|x|','abs','fn'],['mod','mod','op'],['exp','exp','fn'],['∛','cbrt','fn'],['C','c','fn'],['⌫','bs','fn'],['¹/ₓ','inv','fn'],['÷','/','op'],['x²','sq','fn'],['7','7'],['8','8'],['9','9'],['×','*','op'],['√x','sqrt','fn'],['4','4'],['5','5'],['6','6'],['−','-','op'],['%','pct','fn'],['1','1'],['2','2'],['3','3'],['+','+','op'],['CE','ce','fn'],['+/−','neg'],['0','0'],[',','.'],['=','=','eq']];
 function keys(){const K=sci?SCI:STD;const k=$('.calc-keys',root);k.style.gridTemplateColumns=`repeat(${sci?5:4},1fr)`;k.innerHTML=K.map(([l,v,c])=>`<button class="ck${c?' '+c:' dg'}" data-k="${v}">${l}</button>`).join('');$('.mn',root).textContent=sci?'Инженерный':'Обычный';$('[data-a=deg]',root).style.display=sci?'':'none';$('[data-a=deg]',root).textContent=deg?'DEG':'RAD';
  if(!win.maximized){const r=WM.rect(win);if(sci&&r.h<620)WM.setRect(win,{h:Math.min(640,WM.H-r.y)});}}
 const pretty=s=>s.replace(/\*/g,' × ').replace(/\//g,' ÷ ').replace(/(\d|\))-/g,'$1 − ').replace(/\+/g,' + ').replace(/\^/g,' ^ ').replace(/mod/g,' mod ').replace(/\./g,',');
 const show=()=>{$('.rs',root).textContent=entry.replace('.',',').replace(/\B(?=(\d{3})+(?!\d))/g,m=>entry.includes('.')&&entry.indexOf('.')<entry.length?m:m);$('.ex',root).textContent=pretty(expr);const r=$('.rs',root);r.style.fontSize=entry.length>16?'26px':entry.length>11?'34px':'';};
 const num=()=>{const v=parseFloat(entry);return isNaN(v)?0:v;};
 const err=m=>{entry=m;fresh=true;expr='';show();entry='0';};
 function un(f,label){try{const v=num();let r;const D=deg?Math.PI/180:1;switch(f){case 'inv':if(v===0)return err('Деление на ноль невозможно');r=1/v;break;case 'sq':r=v*v;break;case 'sqrt':if(v<0)return err('Недопустимый ввод');r=Math.sqrt(v);break;case 'neg':r=-v;break;
   case 'sin':r=Math.sin(v*D);break;case 'cos':r=Math.cos(v*D);break;case 'tan':r=Math.tan(v*D);break;case 'ln':if(v<=0)return err('Недопустимый ввод');r=Math.log(v);break;case 'log':if(v<=0)return err('Недопустимый ввод');r=Math.log10(v);break;case 'fact':r=evalExpr(v+'!');break;case 'p10':r=Math.pow(10,v);break;case 'abs':r=Math.abs(v);break;case 'exp':r=Math.exp(v);break;case 'cbrt':r=Math.cbrt(v);break;
   case 'pct':{const m=/([\d.]+)[+\-]$/.exec(expr);r=m?parseFloat(m[1])*v/100:v/100;break;}}
   if(Math.abs(r)<1e-13)r=0;entry=fmtNum(r);fresh=f!=='neg';show();}catch(e){err(e.message);}}
 function press(k){Sound.click&&0;if(/^\d$/.test(k)){entry=fresh||entry==='0'?k:(entry.length<20?entry+k:entry);fresh=false;}
  else if(k==='.'){if(fresh){entry='0.';fresh=false;}else if(!entry.includes('.'))entry+='.';}
  else if(['+','-','*','/','^','mod'].includes(k)){if(expr.endsWith(')')&&fresh)expr+=k;else if(fresh&&/[+\-*/^d]$/.test(expr))expr=expr.replace(/(mod|[+\-*/^])$/,k);else expr+=(entry.startsWith('-')?'('+entry+')':entry)+k;fresh=true;}
  else if(k==='='){let full=expr;if(!(expr.endsWith(')')&&fresh))full+=entry.startsWith('-')?'('+entry+')':entry;full+=')'.repeat(Math.max(0,parens));if(!full)return;
   try{const r=evalExpr(full,deg);const rs=fmtNum(Math.abs(r)<1e-13?0:r);hist.unshift({e:pretty(full)+' =',r:rs});hist=hist.slice(0,50);LS.set('calcHist',hist);renderHist();$('.ex',root).textContent=pretty(full)+' =';entry=rs;expr='';parens=0;fresh=true;$('.rs',root).textContent=entry.replace('.',',');return;}catch(e){return err(e.message);}}
  else if(k==='c'){expr='';entry='0';fresh=true;parens=0;}else if(k==='ce'){entry='0';fresh=true;}
  else if(k==='bs'){if(!fresh){entry=entry.length>1?entry.slice(0,-1):'0';if(entry==='-')entry='0';}}
  else if(k==='pi'){entry=fmtNum(Math.PI);fresh=true;}else if(k==='e'){entry=fmtNum(Math.E);fresh=true;}
  else if(k==='('){expr+=(!fresh&&entry!=='0'?entry+'*':'')+'(';parens++;entry='0';fresh=true;}
  else if(k===')'){if(parens>0){if(!(expr.endsWith(')')&&fresh))expr+=entry;expr+=')';parens--;fresh=true;try{entry=fmtNum(evalExpr(expr.slice(expr.lastIndexOf('(',expr.length-2)),deg));}catch(e){}}}
  else return un(k);show();}
 function renderHist(){$('.list',root).innerHTML=hist.length?hist.map((h,i)=>`<div class="he" data-i="${i}"><small>${esc(h.e)}</small><b>${esc(h.r.replace('.',','))}</b></div>`).join(''):'<div class="muted" style="font-size:13px;padding:8px">Журнал пока пуст</div>';}
 function histVis(){const w=root.clientWidth;$('.calc-hist',root).style.display=showHist&&w>520?'':'none';}
 root.addEventListener('click',e=>{const b=e.target.closest('[data-k]');if(b){press(b.dataset.k);return;}const h=e.target.closest('.he');if(h){entry=hist[+h.dataset.i].r;fresh=true;show();}
  const a=e.target.closest('[data-a]')?.dataset.a;if(a==='mode'){Shell.menu(e.clientX,e.clientY+10,[{label:'Обычный',checked:!sci,action:()=>{sci=false;LS.set('calcSci',sci);keys();}},{label:'Инженерный',checked:sci,action:()=>{sci=true;LS.set('calcSci',sci);keys();}}]);}
  if(a==='deg'){deg=!deg;keys();}if(a==='hist'){showHist=!showHist;histVis();}if(a==='clrh'){hist=[];LS.set('calcHist',hist);renderHist();}});
 root.tabIndex=0;root.addEventListener('keydown',e=>{const k=e.key;const map={Enter:'=','=':'=',Escape:'c',Backspace:'bs',Delete:'ce',',':'.','.':'.','+':'+','-':'-','*':'*','/':'/','^':'^','(':'(',')':')','%':'pct'};if(/^\d$/.test(k))press(k);else if(map[k]){e.preventDefault();press(map[k]);}else if(e.ctrlKey&&k==='c')navigator.clipboard?.writeText(entry);else return;const b=$(`[data-k="${CSS.escape(/^\d$/.test(k)?k:map[k])}"]`,root);if(b){b.classList.add('pressed');setTimeout(()=>b.classList.remove('pressed'),120);}});
 keys();renderHist();show();setTimeout(()=>{root.focus();histVis();},60);win.onFocus=()=>setTimeout(()=>root.focus({preventScroll:true}),0);return win;}});

/* ============================ SETTINGS ============================ */
const ACCENTS=['#0078d4','#0063b1','#8e8cd8','#6b69d6','#8764b8','#b146c2','#c239b3','#e3008c','#ea005e','#e81123','#d13438','#ca5010','#f7630c','#ff8c00','#ffb900','#498205','#10893e','#00b294','#038387','#2d7d9a','#00b7c3','#567c73','#7a7574','#69797e'];
Apps.register('settings',{name:'Параметры',icon:AI.settings,single:true,keywords:'settings настройки параметры обои тема control',
 onReopen(win,o){if(o&&o.page)win._go(o.page);},
 launch(o){const PG=[['system','Система',I.sys],['personal','Персонализация',I.brush2],['apps','Приложения',I.apps],['about','О системе',I.info]];
 const root=el(`<div style="display:flex;flex:1;min-height:0"><div class="st-side"><div class="st-user"><span class="avatar">${AI.user()}</span><div><b class="un"></b><div class="muted" style="font-size:12px">Локальная учётная запись</div></div></div><div class="addr" style="margin:0 4px 12px;height:34px"><input placeholder="Найти параметр" class="sq"><span class="ico" style="width:14px;height:14px;opacity:.6">${I.search}</span></div>${PG.map(p=>`<div class="si" data-p="${p[0]}"><span class="ico">${p[2]}</span>${p[1]}</div>`).join('')}</div><div class="st-main"></div></div>`);
 const win=WM.create({app:'settings',title:'Параметры',icon:AI.settings(),width:960,height:640,content:root,minW:640,minH:400});
 const main=$('.st-main',root);let page=o.page||'system';
 const tg=(k,inv)=>`<div class="toggle${!!Settings.get(k)!==!!inv?' on':''}" data-tg="${k}" role="switch"></div>`;
 const row=(ic,t,s,ctl)=>`<div class="srow"><span class="ico">${ic}</span><div class="tx">${t}<small>${s||''}</small></div>${ctl||''}</div>`;
 function render(){$('.un',root).textContent=Settings.get('user');$$('.st-side .si',root).forEach(s=>s.classList.toggle('on',s.dataset.p===page));const S=Settings;let h='';
  if(page==='system'){h=`<h1>Система</h1><div class="srow" style="min-height:100px"><span style="width:120px;height:72px;border-radius:6px;background-size:cover;background-position:center;background-image:${esc(Shell.wallCss(S.get('wallpaper')))};flex:none;border:1px solid var(--border)"></span><div class="tx"><b style="font-size:18px">WIN11-WEB</b><small>Virtual Browser PC · <a href="#" data-a="rename" style="color:var(--accent-text)">Переименовать</a></small></div><div style="display:flex;gap:18px;font-size:12px"><div>${AI.cloud()}<br>OneDrive</div></div></div>
   <h3>Дисплей</h3>${row(I.sun,'Яркость','Настройка яркости встроенного дисплея',`<input type="range" min="20" max="100" value="${S.get('brightness')}" data-rg="brightness">`)}${row(I.moon,'Ночной свет','Использовать более тёплые цвета для снижения синего света',tg('nightLight'))}
   <h3>Звук</h3>${row(I.vol,'Громкость','Динамики (Web Audio)',`<input type="range" min="0" max="100" value="${S.get('volume')}" data-rg="volume">`)}${row(I.bell,'Системные звуки','Звуки запуска, уведомлений и ошибок',tg('sounds'))}${row(I.run,'Проверить звук','Воспроизвести мелодию запуска Windows 11','<button class="btn" data-a="snd">Воспроизвести</button>')}
   <h3>Уведомления и питание</h3>${row(I.bell,'Уведомления','Получать уведомления от приложений',tg('notifications'))}${row(I.wifi,'Wi-Fi','Домашняя сеть 5G',tg('wifi'))}${row(I.bt,'Bluetooth','Обнаружение устройств',tg('bt'))}${row(I.battery,'Батарея',`${Shell.battery}% · примерно 5 ч 12 мин`,`<div style="width:120px;height:6px;border-radius:3px;background:var(--border-2)"><div style="width:${Shell.battery}%;height:100%;border-radius:3px;background:#3fb950"></div></div>`)}
   <h3>Хранилище</h3>${row(AI.drive(),'Локальный диск (C:)',`Используется ${fmtSize(usedBytes())} из ~5 МБ (localStorage)`,`<button class="btn" data-a="exp">Открыть</button>`)}`;}
  if(page==='personal'){const cw=LS.get('customWall',null);h=`<h1>Персонализация</h1><div class="st-prev" style="background-image:${esc(Shell.wallCss(S.get('wallpaper')))}"><div class="st-prev-win"></div><div class="st-prev-tb"></div></div>
   <h3>Фон</h3><div class="srow" style="flex-wrap:wrap"><div class="tx">Выберите изображение<small>Обои нарисованы чистым CSS/SVG</small></div><div style="display:flex;gap:8px;flex-wrap:wrap">${[['bloom-dark','Bloom Dark'],['bloom-light','Bloom Light'],['cyberpunk','Cyberpunk'],['abstract','Абстракция'],...(cw?[['custom','Моё фото']]:[])].map(([k,n])=>`<button class="wallthumb${S.get('wallpaper')===k?' on':''}" data-w="${k}" title="${n}" style="background-image:${esc(Shell.wallCss(k))}"></button>`).join('')}</div></div>
   ${row(I.image,'Ваше фото','Загрузите собственное изображение с компьютера','<label class="btn" style="cursor:pointer">Обзор фото<input type="file" accept="image/*" hidden data-a="upload"></label>')}
   <h3>Цвета</h3>${row(I.theme,'Режим','Светлая или тёмная тема для Windows и приложений',`<select class="inp" data-sel="theme" style="width:140px"><option value="dark"${S.get('theme')==='dark'?' selected':''}>Тёмный</option><option value="light"${S.get('theme')==='light'?' selected':''}>Светлый</option></select>`)}
   ${row(I.view,'Эффекты прозрачности','Mica и Acrylic — полупрозрачные окна и панели',tg('transparency'))}
   <div class="srow" style="flex-direction:column;align-items:stretch"><div class="tx">Акцентный цвет<small>Используется для кнопок, переключателей и выделения</small></div><div class="accents">${ACCENTS.map(c=>`<button data-ac="${c}" style="background:${c}" class="${S.get('accent')===c?'on':''}"></button>`).join('')}<label title="Свой цвет" style="position:relative;overflow:hidden;background:conic-gradient(red,yellow,lime,cyan,blue,magenta,red)" class="acc-custom"><input type="color" value="${S.get('accent')}" data-a="acc" style="opacity:0;position:absolute;inset:0;cursor:pointer"></label></div></div>
   <h3>Рабочий стол</h3>${row(I.view,'Размер значков','',`<select class="inp" data-sel="iconSize" style="width:140px">${[['s','Мелкие'],['m','Обычные'],['l','Крупные']].map(([v,n])=>`<option value="${v}"${S.get('iconSize')===v?' selected':''}>${n}</option>`).join('')}</select>`)}`;}
  if(page==='apps'){h=`<h1>Приложения</h1><h3>Установленные приложения</h3>${Object.values(Apps.reg).filter(a=>!a.hidden).sort((a,b)=>a.name.localeCompare(b.name,'ru')).map(a=>`<div class="srow"><span class="ico" style="width:28px;height:28px">${a.icon()}</span><div class="tx">${esc(a.name)}<small>Microsoft Corporation · ${(8+a.name.length*1.7).toFixed(1)} МБ · ${Apps.pinned.includes(a.id)?'Закреплено в «Пуск»':'Встроенное'}</small></div><span class="muted" style="font-size:12px">${WM.byApp(a.id).length?'Запущено':''}</span><button class="btn" data-open="${a.id}">Открыть</button></div>`).join('')}
   <h3>Приложения по умолчанию</h3>${row(I.file,'.txt, .md, .log, .json','Блокнот')}${row(I.image,'.png, .jpg, .gif, .webp','Фотографии')}${row(I.folder,'Папки','Проводник')}`;}
  if(page==='about'){const nav=navigator;h=`<h1>О системе</h1><div class="srow"><span class="ico" style="width:36px;height:36px">${AI.pc()}</span><div class="tx"><b>WIN11-WEB</b><small>Virtual Browser PC</small></div><button class="btn" data-a="rename">Переименовать пользователя</button></div>
   <h3>Характеристики устройства</h3><div class="srow sel-text" style="display:grid;grid-template-columns:200px 1fr;gap:8px 16px"><span class="muted">Имя устройства</span><span>WIN11-WEB</span><span class="muted">Процессор</span><span>Virtual Web CPU (${nav.hardwareConcurrency||4} ядер) @ 3.60 ГГц</span><span class="muted">ОЗУ</span><span>${nav.deviceMemory?nav.deviceMemory+' ГБ (физич.)':'16,0 ГБ'}</span><span class="muted">Тип системы</span><span>64-разрядная ОС, процессор x64</span><span class="muted">Экран</span><span>${screen.width}×${screen.height}, ${devicePixelRatio}x</span></div>
   <h3>Характеристики Windows</h3><div class="srow sel-text" style="display:grid;grid-template-columns:200px 1fr;gap:8px 16px"><span class="muted">Выпуск</span><span>Windows 11 Web Edition</span><span class="muted">Версия</span><span>23H2</span><span class="muted">Сборка ОС</span><span>22631.4317</span><span class="muted">Браузер</span><span style="font-size:12px">${esc(nav.userAgent)}</span></div>
   ${row(I.info,'О программе Windows','winver','<button class="btn" data-open="winver">Открыть</button>')}
   <h3>Восстановление</h3>${row(I.restart,'Вернуть компьютер в исходное состояние (Reset System Data)','Удалит все файлы VFS, рекорды, заметки и настройки','<button class="btn danger" data-a="reset">Сбросить</button>')}`;}
  main.innerHTML=h;main.scrollTop=0;}
 function go(p){page=p;render();}win._go=go;
 root.addEventListener('click',async e=>{const s=e.target.closest('.st-side .si');if(s)return go(s.dataset.p);
  const t=e.target.closest('[data-tg]');if(t){const k=t.dataset.tg;Settings.set(k,!Settings.get(k));t.classList.toggle('on',!!Settings.get(k));Sound.click();return;}
  const w=e.target.closest('[data-w]');if(w){Settings.set('wallpaper',w.dataset.w);render();return;}
  const ac=e.target.closest('[data-ac]');if(ac){Settings.set('accent',ac.dataset.ac);$$('[data-ac]',main).forEach(b=>b.classList.toggle('on',b===ac));return;}
  const op=e.target.closest('[data-open]');if(op)return Apps.launch(op.dataset.open);
  const a=e.target.closest('[data-a]')?.dataset.a;if(a==='snd')Sound.startup();if(a==='exp')Apps.launch('explorer',{path:'C:\\'});
  if(a==='rename'){e.preventDefault();const n=await Shell.prompt('Имя пользователя','Новое имя:',Settings.get('user'));if(n&&n.trim()){Settings.set('user',n.trim().slice(0,24));render();}}
  if(a==='reset'){if(await Shell.confirm('Сброс системы','Все файлы, настройки и рекорды будут удалены без возможности восстановления. Продолжить?')){LS.clear();location.reload();}}});
 root.addEventListener('input',e=>{const r=e.target.closest('[data-rg]');if(r)Settings.set(r.dataset.rg,+r.value);if(e.target.dataset.a==='acc')Settings.set('accent',e.target.value);});
 root.addEventListener('change',e=>{const s=e.target.closest('[data-sel]');if(s){if(s.dataset.sel==='theme')Shell.setTheme(s.value);else Settings.set(s.dataset.sel,s.value);render();}
  if(e.target.dataset.a==='upload'&&e.target.files[0]){const f=e.target.files[0];const rd=new FileReader();rd.onload=()=>{const im=new Image();im.onload=()=>{const sc=Math.min(1,1920/im.width,1080/im.height);const c=document.createElement('canvas');c.width=im.width*sc|0;c.height=im.height*sc|0;c.getContext('2d').drawImage(im,0,0,c.width,c.height);
   let d=c.toDataURL('image/jpeg',.82);if(d.length>2.4e6)d=c.toDataURL('image/jpeg',.6);try{localStorage.setItem('w11.customWall',JSON.stringify(d));Settings.set('wallpaper','custom');Shell.applyWallpaper();render();Shell.notify({title:'Обои обновлены',body:f.name,icon:AI.settings(),app:'Параметры',silent:true});}catch(err){Shell.alert('Параметры','Изображение слишком большое для хранилища браузера.');}};im.src=rd.result;};rd.readAsDataURL(f);}});
 $('.sq',root).addEventListener('input',e=>{const q=e.target.value.toLowerCase().trim();if(!q)return render();const map=[['обои фон фото wallpaper','personal'],['тема темная светлая цвет акцент прозрач','personal'],['яркость звук громкость уведомления wi-fi bluetooth батарея ночной диск','system'],['приложения программы','apps'],['сброс версия о системе reset имя','about']];const m=map.find(([k])=>k.split(' ').some(w=>w.startsWith(q)||q.startsWith(w)));if(m&&m[1]!==page)go(m[1]);});
 Bus.on('setting',(k)=>{if(win.el.isConnected&&['theme','wallpaper','wifi','bt'].includes(k)&&!main.contains(document.activeElement))render();});
 render();return win;}});

/* ============================ COPILOT ============================ */
const Copilot={built:false,
 jokes:['Почему программисты путают Хэллоуин и Рождество? Потому что 31 OCT = 25 DEC 🎃🎄','— Сколько нужно программистов, чтобы заменить лампочку?\n— Ни одного. Это аппаратная проблема.','Я бы рассказал шутку про UDP, но не уверен, что ты её получишь.','У Windows есть три состояния: «работает», «обновляется» и «сейчас будет обновляться». Хорошо, что я веб-версия 😌','Есть 10 типов людей: те, кто понимает двоичную систему, и те, кто нет.','— Доктор, у меня синий экран!\n— А вы пробовали выключить и включить?\n— Это и было лечением.'],
 tips:['Win + D — свернуть все окна и показать рабочий стол. Если браузер перехватывает Win, используй Alt+Shift+D.','Наведи курсор на кнопку «Развернуть» — появится Snap Layouts. А ещё можно тащить окно к краю экрана.','В Терминале попробуй команды matrix, neofetch и color 0A 😎','В Сапёре двойной щелчок по цифре открывает всех соседей, если флажки расставлены.','Alt + Tab переключает окна. Все файлы сохраняются в localStorage — они переживут перезагрузку страницы.','В Диспетчере задач можно снять задачу explorer.exe… или даже csrss.exe, если тебе не страшно 🙈'],
 render(){const p=$('#copilot');if(this.built&&p.childElementCount)return setTimeout(()=>$('#cpIn')?.focus(),250);this.built=true;
  p.innerHTML=`<div class="cp-head"><span class="ic">${AI.copilot()}</span><div style="flex:1"><b>Copilot</b><div class="muted" style="font-size:12px">Ваш помощник в Windows</div></div><button class="tbtn" data-cp="clear" title="Новая тема"><span class="ico">${I.newi}</span></button><button class="tbtn" data-cp="close" title="Закрыть"><span class="ico">${I.close}</span></button></div><div class="cp-msgs"></div><div class="cp-chips">${['Включи тёмную тему','Открой сапёр','Расскажи шутку','Дай совет','Какая погода?','Сколько будет 12*34+5?'].map(c=>`<button class="chip">${c}</button>`).join('')}</div><form class="cp-input"><input id="cpIn" placeholder="Спросите о чём угодно…" autocomplete="off"><button type="submit" title="Отправить"><span class="ico" style="width:16px;height:16px">${I.send}</span></button></form>`;
  $('form',p).onsubmit=e=>{e.preventDefault();const v=$('#cpIn').value.trim();if(v){$('#cpIn').value='';this.ask(v);}};
  p.addEventListener('click',e=>{const c=e.target.closest('.chip');if(c)this.ask(c.textContent);const a=e.target.closest('[data-cp]')?.dataset.cp;if(a==='close')Shell.closePanels();if(a==='clear'){$('.cp-msgs',p).innerHTML='';this.greet();}});
  this.greet();setTimeout(()=>$('#cpIn')?.focus(),250);},
 greet(){const h=new Date().getHours();this.add(`${h<6?'Доброй ночи':h<12?'Доброе утро':h<18?'Добрый день':'Добрый вечер'}, ${Settings.get('user')}! 👋\nЯ Copilot. Могу управлять системой (тема, громкость, обои), открывать приложения, считать, шутить и подсказывать. Напиши «помощь», чтобы увидеть всё.`,'bot');},
 add(t,who){const m=$('#copilot .cp-msgs');const d=document.createElement('div');d.className='msg '+who;d.textContent=t;m.appendChild(d);m.scrollTop=m.scrollHeight;return d;},
 async ask(q){this.add(q,'me');const m=$('#copilot .cp-msgs');const ty=el('<div class="msg bot typing"><span></span><span></span><span></span></div>');m.appendChild(ty);m.scrollTop=m.scrollHeight;
  await sleep(450+Math.random()*600);ty.remove();let r;try{r=this.reply(q);}catch(e){r='Хм, что-то пошло не так: '+e.message;}this.add(r,'bot');Sound.pop();},
 reply(q){const s=q.toLowerCase().replace(/ё/g,'е');const has=(...w)=>w.some(x=>s.includes(x));
  const APPS=[[['сапер','minesweeper','мин'],'minesweeper'],[['косынк','пасьянс','solitaire','карт'],'solitaire'],[['блокнот','notepad'],'notepad'],[['paint','пеинт','рисова'],'paint'],[['терминал','powershell','консол','cmd','командн'],'terminal'],[['калькулятор','calc'],'calc'],[['диспетчер','task manager','taskmgr'],'taskmgr'],[['параметр','настройк','settings'],'settings'],[['проводник','explorer','файл'],'explorer'],[['фото','картин','viewer'],'viewer']];
  if(has('помощ','help','что ты умеешь','команд'))return 'Вот что я умею:\n• «включи тёмную / светлую тему»\n• «открой сапёр / косынку / paint / терминал…»\n• «закрой все окна», «покажи рабочий стол»\n• «смени обои», «поставь синий / красный акцент»\n• «громкость 50», «выключи звук», «яркость 70»\n• «сколько будет 2^10», «который час», «погода»\n• «создай заметку купить хлеб»\n• «шутка», «совет», «система»\n• «заблокируй», «перезагрузи», «синий экран»';
  if(has('темн','dark','ночную тем')&&has('тем','dark','режим')){Shell.setTheme('dark');return 'Готово! 🌙 Тёмная тема включена — глаза скажут спасибо.';}
  if(has('светл','light','дневн')&&has('тем','light','режим')){Shell.setTheme('light');return 'Готово! ☀️ Светлая тема включена.';}
  if(has('смени тему','переключи тему','другую тему')){const t=Settings.get('theme')==='dark'?'light':'dark';Shell.setTheme(t);return 'Тема переключена на '+(t==='dark'?'тёмную 🌙':'светлую ☀️');}
  if(has('синий экран','bsod','краш','урони')){setTimeout(()=>Shell.bsod('COPILOT_TOLD_ME_TO'),1200);return 'Ну, ты сам попросил… 💀';}
  if(has('заблокир','lock')){setTimeout(()=>Shell.lock(),800);return 'Блокирую компьютер 🔒';}
  if(has('перезагруз','restart','рестарт')){setTimeout(()=>Shell.restart(),1000);return 'Перезагружаюсь… Увидимся через пару секунд!';}
  if(has('выключи комп','завершение работы','shutdown','выключи пк')){setTimeout(()=>Shell.shutdown(),1000);return 'Завершаю работу. Пока! 👋';}
  if(has('закрой все','close all')){const n=WM.all().length;WM.all().forEach(w=>{w.onClose=null;WM.close(w);});return n?`Закрыл окон: ${n} ✨`:'Открытых окон и так нет.';}
  if(has('рабочий стол','сверни все')){WM.showDesktop();return 'Вот твой рабочий стол 🖥️';}
  const vm=/(громкост|звук)\D*(\d{1,3})/.exec(s);if(vm){Settings.set('volume',clamp(+vm[2],0,100));return `Громкость: ${clamp(+vm[2],0,100)}% 🔊`;}
  if(has('выключи звук','без звука','mute','тише некуда')){Settings.set('volume',0);return 'Звук выключен 🔇';}
  if(has('громче')){Settings.set('volume',clamp(Settings.get('volume')+20,0,100));return 'Громкость: '+Settings.get('volume')+'% 🔊';}if(has('тише')){Settings.set('volume',clamp(Settings.get('volume')-20,0,100));return 'Громкость: '+Settings.get('volume')+'% 🔉';}
  if(has('включи звук')){Settings.set('volume',60);return 'Звук включён, 60% 🔊';}
  const bm=/яркост\D*(\d{1,3})/.exec(s);if(bm){Settings.set('brightness',clamp(+bm[1],20,100));return `Яркость: ${clamp(+bm[1],20,100)}% 🔆`;}
  if(has('ночной свет')){Settings.set('nightLight',!has('выкл'));return 'Ночной свет '+(Settings.get('nightLight')?'включён 🌅':'выключен');}
  if(has('обои','wallpaper','фон')){const W=['bloom-dark','bloom-light','cyberpunk','abstract'];const pick=has('кибер','cyber')?'cyberpunk':has('абстрак')?'abstract':has('светл')?'bloom-light':has('темн')?'bloom-dark':W[(W.indexOf(Settings.get('wallpaper'))+1)%W.length];Settings.set('wallpaper',pick);return 'Обои изменены на «'+{'bloom-dark':'Bloom Dark','bloom-light':'Bloom Light',cyberpunk:'Cyberpunk',abstract:'Абстракция'}[pick]+'» 🎨';}
  const AC={син:'#0078d4',красн:'#e81123',зелен:'#10893e',фиолет:'#8764b8',оранж:'#f7630c',розов:'#e3008c',желт:'#ffb900',бирюз:'#00b7c3',сер:'#69797e'};if(has('акцент','цвет')){const k=Object.keys(AC).find(k=>s.includes(k));if(k){Settings.set('accent',AC[k]);return 'Акцентный цвет изменён ✅';}}
  if(has('открой','запусти','включи','open','сыгра','играть','покажи')){const a=APPS.find(([k])=>k.some(x=>s.includes(x)));if(a){Apps.launch(a[1]);return `Открываю «${Apps.get(a[1]).name}» 🚀`;}if(has('игр')){Apps.launch(Math.random()<.5?'minesweeper':'solitaire');return 'Давай сыграем! 🎮';}}
  const nm=/(?:заметку|записку|запиши|напомни)[:\s]+(.+)/i.exec(q);if(nm){const p=VFS.uniqueName('C:\\Users\\User\\Desktop','Заметка Copilot','.txt');VFS.write('C:\\Users\\User\\Desktop\\'+p,nm[1]+'\n\n— '+new Date().toLocaleString('ru-RU'));return `Сохранил заметку «${p}» на рабочий стол 📝`;}
  const mm=/(?:сколько( будет)?|посчитай|вычисли|реши|=)?\s*([-\d(.,][\d\s+\-*/^().,!%a-z×÷]*)\??$/i.exec(s);if(mm&&/\d/.test(mm[2])&&/[+\-*/^!]|sqrt|sin|cos/.test(mm[2])){try{return `${mm[2].trim()} = ${fmtNum(evalExpr(mm[2].replace(/\?/g,'')))} 🧮`;}catch(e){}}
  if(has('время','час','time')&&!has('част')){const d=new Date();return `Сейчас ${pad(d.getHours())}:${pad(d.getMinutes())} ⏰`;}
  if(has('дата','число','день недели','какой сегодня')){const d=new Date();return `Сегодня ${DAYS[d.getDay()].toLowerCase()}, ${d.getDate()} ${MONTHS_G[d.getMonth()]} ${d.getFullYear()} г. 📅`;}
  if(has('погод','weather','температур','дождь')){const w=Shell.weather||{t:12,d:'Переменная облачность'};return `Сейчас ${w.t}°C, ${String(w.d||w.desc||'').toLowerCase()} ⛅ (симуляция). Подробнее — в панели виджетов слева.`;}
  if(has('шут','анекдот','joke','рассмеши','смешн'))return this.jokes[Math.random()*this.jokes.length|0];
  if(has('совет','подсказ','tip','лайфхак'))return '💡 '+this.tips[Math.random()*this.tips.length|0];
  if(has('систем','цп','памят','нагрузк','cpu','ram'))return `ЦП: ${Math.round(Monitor.cpu)}% · Память: ${Math.round(Monitor.ram)}% · Окон открыто: ${WM.all().length} · VFS: ${fmtSize(usedBytes())}\nДля деталей открой Диспетчер задач.`;
  if(has('привет','здравств','hello','hi ','хай','добрый'))return `Привет, ${Settings.get('user')}! Чем помочь? 😊`;
  if(has('кто ты','ты кто','твое имя'))return 'Я Copilot — встроенный помощник этой веб-версии Windows 11. Работаю полностью локально, без интернета 🤖';
  if(has('спасиб','thank','благодар'))return 'Всегда пожалуйста! 💙';
  if(has('как дела','как ты'))return 'Отлично! ЦП загружен всего на '+Math.round(Monitor.cpu)+'%, так что я полон сил 💪 А у тебя?';
  const app=APPS.find(([k])=>k.some(x=>s.includes(x)));if(app){Apps.launch(app[1]);return `Открываю «${Apps.get(app[1]).name}» 🚀`;}
  const fb=['Интересный вопрос! Но я пока локальный помощник и умею управлять системой. Напиши «помощь» 🙂','Не совсем понял. Попробуй: «открой paint», «смени обои» или «расскажи шутку».','Хмм… 🤔 Давай лучше сыграем в Сапёра? Напиши «открой сапёр».'];return fb[Math.random()*fb.length|0];}
};
